export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_SCREEN = 'USER_LOGIN_SCREEN'

export const VERIFYING_LOGIN_STATUS = 'VERIFYING_LOGIN_STATUS'
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'

export const FETCHING_NOTIFICATION = 'FETCHING_NOTIFICATION'

export const FETCHING_NOTIFICATION_SUCCESS = 'FETCHING_NOTIFICATION_SUCCESS'

export const FETCHING_NOTIFICATION_FAILURE = 'FETCHING_NOTIFICATION_FAILURE'


export const FETCHING_TRANSACTION = 'FETCHING_TRANSACTION'

export const FETCHING_TRANSACTION_SUCCESS = 'FETCHING_TRANSACTION_SUCCESS'

export const FETCHING_TRANSACTION_FAILURE = 'FETCHING_TRANSACTION_FAILURE'

export const LOG_IN = 'LOG_IN'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'
export const LOG_OUT = 'LOG_OUT'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const SHOW_SIGN_IN_CONFIRMATION_MODAL = 'SHOW_SIGN_IN_CONFIRMATION_MODAL';
export const SHOW_SIGN_UP_CONFIRMATION_MODAL = 'SHOW_SIGN_UP_CONFIRMATION_MODAL';

export const CONFIRM_SIGNUP = 'CONFIRM_SIGNUP';
export const CONFIRM_SIGNUP_SUCCESS = 'CONFIRM_SIGNUP_SUCCESS';
export const CONFIRM_SIGNUP_FAILURE = 'CONFIRM_SIGNUP_FAILURE';

export const CONFIRM_LOGIN = 'CONFIRM_LOGIN';
export const CONFIRM_LOGIN_SUCCESS = 'CONFIRM_LOGIN_SUCCESS';
export const CONFIRM_LOGIN_FAILURE = 'CONFIRM_LOGIN_FAILURE';

export const RECIEVED_NOTIFICATION = 'RECIEVED_NOTIFICATION';


export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const INCREASE_PRODUCT_IN_CART = 'INCREASE_PRODUCT_IN_CART';
export const DECREASE_PRODUCT_IN_CART = 'DECREASE_PRODUCT_IN_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_ORDER = 'ADD_ORDER';
export const EMPTY_CART = 'EMPTY_CART';

export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const FETCHING_PRODUCTS_SUCCESS = 'FETCHING_PRODUCTS_SUCCESS';
export const FETCHING_PRODUCTS_FAILURE = 'FETCHING_PRODUCTS_FAILURE';
export const GET_PRODUCT_IN_CART_COUNT = 'GET_PRODUCT_IN_CART_COUNT';
export const ADD_PRODUCT_TO_SELECTION = 'ADD_PRODUCT_TO_SELECTION';
export const REMOVE_PRODUCT_FROM_SELECTION = 'REMOVE_PRODUCT_FROM_SELECTION';

export const ADD_CARD = 'ADD_CARD'
export const MAKE_PAYMENT = 'MAKE_PAYMENT'
export const PAYMENT_SUCCESSFUL = 'PAYMENT_SUCCESSFUL'
export const PAYMENT_FAILED = 'PAYMENT_FAILED'

export const PASSWORD_RECOVERY_SUCCESS = 'PASSWORD_RECOVERY_SUCCESS'
export const PASSWORD_RECOVERY_FAILURE = 'PASSWORD_RECOVERY_FAILURE'

export const FETCHING_INVESTMENT = 'FETCHING_INVESTMENT'
export const FETCHING_INVESTMENT_SUCCESS = 'FETCHING_INVESTMENT_SUCCESS'
export const FETCHING_INVESTMENT_FAILURE = 'FETCHING_INVESTMENT_FAILURE'


export const CREATE_FARM = 'CREATE_FARM'
export const CREATE_FARM_SUCCESS = 'CREATE_FARM_SUCCESS'
export const CREATE_FARM_FAILURE = 'CREATE_FARM_FAILURE'

export const CREATE_CART = 'CREATE_CART'
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS'

export const CREATE_ADDRESS = 'CREATE_ADDRESS'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS'
export const GET_ADDRESS = 'GET_ADDRESS'
export const SELECT_ADDRESS = 'SELECT_ADDRESS'
export const SELECT_ADDRESS_SUCCESS = 'SELECT_ADDRESS_SUCCESS'

export const CREATE_ORDER= 'CREATE_ORDER'
export const CREATE_ORDER_SUCCESS= 'CREATE_ORDER_SUCCESS'

export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER = 'FETCH_ORDER'

export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const GETTING_ORDERS = 'GETTING_ORDERS'
export const GETTING_ORDERS_SUCCESS = 'GETTING_ORDERS_SUCCESS'
export const GETTING_ORDERS_FAILURE = 'GETTING_ORDERS_FAILURE'

export const FETCHING_SAVED_ITEM_SUCCESS = 'FETCHING_SAVED_ITEM_SUCCESS'

export const ADDING_SAVED_ITEM_SUCCESS = 'ADDING_SAVED_ITEM_SUCCESS'

export const REMOVE_SAVED_ITEM_SUCCESS = 'REMOVE_SAVED_ITEM_SUCCESS'

export const LIKE_FEED = 'LIKE_FEED'
export const LIKE_FEED_SUCCESS = 'LIKE_FEED_SUCCESS'
export const LIKE_FEED_FAILURE = 'LIKE_FEED_FAILURE'
export const DIS_LIKE_FEED = 'DIS_LIKE_FEED'
export const DIS_LIKE_FEED_SUCCESS = 'DIS_LIKE_FEED_SUCCESS'
export const DIS_LIKE_FEED_FAILURE = 'DIS_LIKE_FEED_FAILURE'
export const FAVOURITE_FEED = 'FAVOURITE_FEED'
export const FAVOURITE_FEED_SUCCESS = 'FAVOURITE_FEED_SUCCESS'
export const FAVOURITE_FEED_FAILURE = 'FAVOURITE_FEED_FAILURE'
export const UN_FAVOURITE_FEED = 'UN_FAVOURITE_FEED'
export const UN_FAVOURITE_FEED_SUCCESS = 'UN_FAVOURITE_FEED_SUCCESS'
export const UN_FAVOURITE_FEED_FAILURE = 'UN_FAVOURITE_FEED_FAILURE'
export const GET_FEEDS= 'GET_FEEDS'
export const GET_FEEDS_SUCCESS= 'GET_FEEDS_SUCCESS'
export const GET_FEEDS_FAILURE= 'GET_FEEDS_FAILURE'

export const FEEDS_UNLIKE = 'FEEDS_UNLIKE'
export const FEEDS_UNDISLIKE = 'FEEDS_UNDISLIKE'

export const REMOVE_CARD = 'REMOVE_CARD'

export const SEND_OTP = 'SEND_OTP'

export const SENDING_OTP = 'SENDING_OTP'

export const FETCHING_SAVED_ITEMS = 'FETCHING_SAVED_ITEMS'
export const FETCHING_SAVED_ITEMS_FAILURE = 'FETCHING_SAVED_ITEMS_FAILURE'

export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'